# Valid item entries can be found at the following link:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

worlds:
  world:
    mode: WHITELIST
    keep-inventory: true
    items:
      - WOODEN_PICKAXE
      - WOODEN_SWORD
  world_the_end:
    mode: BLACKLIST
    keep-inventory: true
    items:
      - STONE_AXE
      - STONE_SHOVEL